---
abstract: 'Perl lint'
author:
  - 'Joshua ben Jore <jjore@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.142690'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: B-Lint
no_index:
  directory:
    - t
    - inc
requires:
  Module::Pluggable: '0'
  if: '0'
version: '1.19'
